### ISSUE TITLE
There are still warnings in ConsentViewController-Swift.h

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#100]
<img width="1072" alt="Bildschirmfoto 2020-03-30 um 10 52 50" src="https://user-images.githubusercontent.com/39526001/77896157-232cc500-7278-11ea-87a4-0dde2bac83a6.png">
<img width="1074" alt="Bildschirmfoto 2020-03-30 um 10 52 10" src="https://user-images.githubusercontent.com/39526001/77896166-2627b580-7278-11ea-8414-ed2596501a54.png">

**Comment by andresilveirah** [comment]
Thank you for the heads up @s-hintz  
I'm not exactly sure how to silence those warnings since the `ConsentViewController-Swift.h` is a autogenerated file. Let me try renaming the arguments in the doc comment from `_` to `rawValue` and `forAuthId` to `authId` and see if this solves the issue.

**Comment by andresilveirah** [comment]
@s-hintz the issue should be fixed now. As soon as it's released I'll ping you and the team on Slack.
