### ISSUE TITLE
[SPRING] Remove force unwraps in code 

### ISSUE THREAD

**Issue by toupper** [SourcePointUSA/ios-cmp-app#101]
There are few force unwrap and force try in code. That could leads to crashes if the operation is not successful. We find it safer to use optional ? in these cases and propagate and error in case it fails. I recommend to use [Swift Lint ](https://github.com/realm/SwiftLint)to encourage these rules.

**Comment by andresilveirah** [comment]
@toupper I'm closing this issue. We've since added SwiftLint and remove as many forced unwraps as we thought was useful.
