### ISSUE TITLE
[SPRING] Add Unit tests

### ISSUE THREAD

**Issue by toupper** [SourcePointUSA/ios-cmp-app#102]
Main functionality should be tested with unit tests. Ideally a continuous integration environment is setup so everytime there is a Pull Request or merge to develop/master these are executed and validated

**Comment by andresilveirah** [comment]
Thank you for bringing this up @toupper
We're currently in the process of covering the whole SDK with unit + integration tests. We do have a set of end-to-end tests that gets triggered on every new PR and merging to develop/master. However those end-to-end tests reside in another repository and are maintained separately.
I'll keep this issue open and reference it when we're ready to merge the unit tests.

**Comment by andresilveirah** [comment]
@toupper I'm closing this issue. We've since raised the amount of unit tests on the SDK. We're using GitHub actions to run the unit tests and swiftlint as well as our own internal CI to run the end-to-end tests.
