### ISSUE TITLE
[SPRING] How to trigger the privacy center directly?

### ISSUE THREAD

**Issue by pkcpkc** [SourcePointUSA/ios-cmp-app#106]
How can we trigger the privacy center directly from our native consent screen and/or our oembed solution?

`cmp.presentPrivacyCenter(callbackOnChangeOrClose);`

**Comment by s-hintz** [comment]
In the example app you will find a method for that.

`consentViewController.loadPrivacyManager()`

**Comment by andresilveirah** [comment]
Thank you for the input @s-hintz 
@pkcpkc I'm closing this issue
