### ISSUE TITLE
[SPRING] Improvement: Do not use GDPRViewController to load the message

### ISSUE THREAD

**Issue by toupper** [SourcePointUSA/ios-cmp-app#111]
Currently we have to instantiate `GDPRConsentViewController` to load the message, and retrieve the values in the delegate. This is suboptiomal, we are loading an UI Component and not showing it.
Ideally we would have a method in the SDK not part of a view controller, and the message is retrieved via a completion handler instead of delegate to make it easier.

**Comment by s-hintz** [comment]
I do not see what this does make easier.

**Comment by toupper** [comment]
I find having a closure easier to read, as the handling would be encapsulated in that function. Given that we as client are not returning anything, and that we just get the result and not a process communication, i think the completion handler patter with closures is more suitable for this case:
https://stablekernel.com/use-blocks-closures-delegates-callbacks/
However this is just a personal opinion, the main problem to be solved is not having to instantiate a view controller for retrieving a model (message).

**Comment by andresilveirah** [comment]
@toupper I tend to agree with you but doing that would require a big refactoring on our SDK and very likely a big API change. I'm closing this issue but I am definitely thinking on a way to extract the logic away from the ViewController
