### ISSUE TITLE
[Spring] Crash in Privacy Manager.

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#119]
We have a UIButton in our app to open the Privacy Manager via IBACTION.
It takes a while until the Privacy Manager is visible.
In the mean time the user is able to hit the button multiple times.
When closing the Privacy Manager it crashes.

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <MainPageViewController: 0x7fb91c016400>.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3dcce __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b3b9b2 objc_exception_throw + 48
	2   UIKitCore                           0x00007fff48582b12 -[UIViewController _presentViewController:withAnimationController:completion:] + 5218
	3   UIKitCore                           0x00007fff48584fd2 __63-[UIViewController _presentViewController:animated:completion:]_block_invoke + 98
	4   UIKitCore                           0x00007fff485854db -[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 511
	5   UIKitCore                           0x00007fff48584f30 -[UIViewController _presentViewController:animated:completion:] + 187
	6   UIKitCore                           0x00007fff4858519c -[UIViewController presentViewController:animated:completion:] + 155
	7   BildNewsPad                         0x0000000104fe39f8 $sSo22MainPageViewControllerC11BildNewsPadE17consentUIWillShowyyF + 952
	8   BildNewsPad                         0x0000000104fe3a6b $sSo22MainPageViewControllerC11BildNewsPadE17consentUIWillShowyyFTo + 43
	9   ConsentViewController               0x00000001064b5e0c $s21ConsentViewController011GDPRConsentbC0C04gdprA10UIWillShowyyF + 188
	10  ConsentViewController               0x00000001064b5ed8 $s21ConsentViewController011GDPRConsentbC0C04gdprA10UIWillShowyyFTo + 24
	11  ConsentViewController               0x00000001064c2f5c $s21ConsentViewController010MessageWebbC0C02onD5ReadyyyFTm + 156
	12  ConsentViewController               0x00000001064c53f3 $s21ConsentViewController010MessageWebbC0C011userContentC0_10didReceiveySo06WKUsergC0C_So08WKScriptD0CtFTf4dnn_n + 579
	13  ConsentViewController               0x00000001064c429f $s21ConsentViewController010MessageWebbC0C011userContentC0_10didReceiveySo06WKUsergC0C_So08WKScriptD0CtFTo + 63
	14  WebKit                              0x00007fff2d408421 _ZN28ScriptMessageHandlerDelegate14didPostMessageERN6WebKit12WebPageProxyEONS0_13FrameInfoDataERN7WebCore21SerializedScriptValueE + 217
	15  WebKit                              0x00007fff2d5b6643 _ZN6WebKit29WebUserContentControllerProxy14didPostMessageERN3IPC10ConnectionEN3WTF16ObjectIdentifierINS_26WebPageProxyIdentifierTypeEEEONS_13FrameInfoDataEyRKNS1_13DataReferenceE + 175
	16  WebKit                              0x00007fff2d7c040a _ZN6WebKit29WebUserContentControllerProxy17didReceiveMessageERN3IPC10ConnectionERNS1_7DecoderE + 146
	17  WebKit                              0x00007fff2d2767ca _ZN3IPC18MessageReceiverMap15dispatchMessageERNS_10ConnectionERNS_7DecoderE + 114
	18  WebKit                              0x00007fff2d4ef6bc _ZN6WebKit15WebProcessProxy17didReceiveMessageERN3IPC10ConnectionERNS1_7DecoderE + 24
	19  WebKit                              0x00007fff2d26617c _ZN3IPC10Connection15dispatchMessageENSt3__110unique_ptrINS_7DecoderENS1_14default_deleteIS3_EEEE + 158
	20  WebKit                              0x00007fff2d2657b1 _ZN3IPC10Connection24dispatchIncomingMessagesEv + 377
	21  JavaScriptCore                      0x00007fff26a71225 _ZN3WTF7RunLoop11performWorkEv + 549
	22  JavaScriptCore                      0x00007fff26a71392 _ZN3WTF7RunLoop11performWorkEPv + 34
	23  CoreFoundation                      0x00007fff23da1c71 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x00007fff23da1b9c __CFRunLoopDoSource0 + 76
	25  CoreFoundation                      0x00007fff23da1374 __CFRunLoopDoSources0 + 180
	26  CoreFoundation                      0x00007fff23d9bf6e __CFRunLoopRun + 974
	27  CoreFoundation                      0x00007fff23d9b884 CFRunLoopRunSpecific + 404
	28  GraphicsServices                    0x00007fff38b5ac1a GSEventRunModal + 139
	29  UIKitCore                           0x00007fff48c19220 UIApplicationMain + 1605
	30  BildNewsPad                         0x0000000104e32c20 main + 112
	31  libdyld.dylib                       0x00007fff519b910d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

<img width="1018" alt="Bildschirmfoto 2020-04-15 um 14 36 49" src="https://user-images.githubusercontent.com/39526001/79337840-8ed48a80-7f26-11ea-8a15-46690a942e01.png">

**Comment by andresilveirah** [comment]
@s-hintz have you solved this issue in your app? We could add a state in the SDK to avoid loading the PM multiple times if there's one PM already being loaded.

**Comment by s-hintz** [comment]
We did not implement a workaround.

**Comment by andresilveirah** [comment]
@s-hintz I believe this issue has been resolved. We now have a flag that indicates the message or privacy manager is being loaded. Now `loadPrivacyManager` and `loadMessage` can be called multiple times and only the first one will take effect.
