### ISSUE TITLE
[Spring] The Privacy Manager is zoomable and scrollable including background.

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#120]
<img width="1018" alt="Bildschirmfoto 2020-04-15 um 14 41 07" src="https://user-images.githubusercontent.com/39526001/79338298-57b2a900-7f27-11ea-936a-16a48309454d.png">
<img width="1018" alt="Bildschirmfoto 2020-04-15 um 14 41 02" src="https://user-images.githubusercontent.com/39526001/79338320-600ae400-7f27-11ea-89f8-9d6f1f56ae19.png">
<img width="1018" alt="Bildschirmfoto 2020-04-15 um 14 40 48" src="https://user-images.githubusercontent.com/39526001/79338330-639e6b00-7f27-11ea-8c10-7cff4b819537.png">

**Comment by s-hintz** [comment]
Zooming is fixed now. But moving the dark background is still possible.

**Comment by andresilveirah** [comment]
@s-hintz we're disabling the "bounce effect" on our ConsentViewController in order to fix the dark background from being movable. As soon as the PR is merged, this issue will be closed. Just keep in mind that the SDK still needs to be released after that.

**Comment by s-hintz** [comment]
Will it be in the release tomorrow?
