### ISSUE TITLE
[SPRING] The SDK can not parse its own JSON

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#122]
For the third time I get an JSON error after trying to add the consent for the purpose "Soziale Netzwerke" in the Privacy Center.

ERROR: Error parsing response from https://wrapper-api.sp-prod.net/tcfv2/v1/gdpr/consent?inApp=true: Optional(Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "uuid", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"uuid\", intValue: nil) (\"uuid\").", underlyingError: nil)))

**Comment by s-hintz** [comment]
Does the server send an error 500 and the SDK ignores the error code and continues trying to parse the JSON?

**Comment by andresilveirah** [comment]
Thanks for raising this issue @s-hintz . I believe, back then, this was a mistake in the campaign/account's configuration. Just to give you a bit more context, the SDK relies on the `Codable` protocol to map between the endpoint's response to one of our classes. If the serialisation goes wrong, we capture the exception, wrap it in one of our own `GDPRConsentViewControllerError` classes and call the `onError` callback. 

Closing this issue as I think there's nothing we can do from the SDK standpoint.

**Comment by s-hintz** [comment]
But why do you try to parse the JSON, when the HTTP status code already indicates an error?
