### ISSUE TITLE
[SPRING] The Privacy Center does not open anymore.

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#126]
We can not open the **Privacy Center** anymore anywhere.

If such bug would happen in a live environment and the user clicks on "show options" and nothing happens, he would likely deinstall the app immediately after first launch.

There is even no log message indicating an error.
So the error handling is broken too.

**Comment by andresilveirah** [comment]
@s-hintz even though we found out the PM wasn't showing due to an ID change on the dashboard, I'll keep this issue opened until we implement an error mechanism for when this happens again.

**Comment by s-hintz** [comment]
Yes. I had the same thought.

**Comment by andresilveirah** [comment]
Just a quick update. We're still working to cover this edge case. It takes some time as we have to mobilise other team's resources.

**Comment by andresilveirah** [comment]
@s-hintz with the release of [5.2.3](https://github.com/SourcePointUSA/ios-cmp-app/releases/tag/5.2.3) this issue should be fixed. Can you validate and let me know?

**Comment by andresilveirah** [comment]
@s-hintz I'm closing this issue, let me know if the issue persists for you.
