### ISSUE TITLE
[SPRING] Unreachable buttons in the Message on iPhone 5 (iOS 10.3.1)

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#128]
1. Not all buttons are visible.
2. The title ist clipped.
3. No button is clickable.
4. So the app is completely unusable.

<img width="504" alt="Bildschirmfoto 2020-04-24 um 10 26 17" src="https://user-images.githubusercontent.com/39526001/80191920-b5757e00-8616-11ea-8c19-edb552cbfd82.png">

<img width="1048" alt="Bildschirmfoto 2020-04-24 um 10 38 09" src="https://user-images.githubusercontent.com/39526001/80192750-f621c700-8617-11ea-944e-76ca464ca8b8.png">
<img width="597" alt="Bildschirmfoto 2020-04-24 um 10 38 02" src="https://user-images.githubusercontent.com/39526001/80192763-fa4de480-8617-11ea-835b-b862eb36ede8.png">

**Comment by andresilveirah** [comment]
@s-hintz are you using the pre-defined `GDPRNativeMessageViewController`?

**Comment by s-hintz** [comment]
Do we need to implement our own controller?

I think our Welt colleagues wanted to implement their own controller.

**Comment by andresilveirah** [comment]
@s-hintz you don't. You may as well use our own view controller. We just haven't spent much time polishing its layout yet. So it's good you're bringing me feedback about it. I'll work on them and update you here.

**Comment by s-hintz** [comment]
Perfect.

**Comment by s-hintz** [comment]
The message in SDK version 5.2.2 is still unusable on iPhone 5.
I do not the see buttons completely.
I can not click them.
I looks as if nothing was changed compared to previous versions.

**Comment by s-hintz** [comment]
Since the GDPRNativeMessageViewController is unusable, we are using the web view alternative.
So for me this bug does not need to be anymore.

**Comment by andresilveirah** [comment]
@s-hintz have you considered implementing your own native message controller? 

The point of `GDPRNativeMessageViewController` was to serve as a base example. Although the changes to its layout are very straight forward and, if this would make your implementation easier, we could prioritise them.

**Comment by haerju** [comment]
@andresilveirah let's close this ticket. This is an accoint specific setup issue.
