### ISSUE TITLE
[SPRING] Button texts in the Message should be in German

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#129]
<img width="584" alt="Bildschirmfoto 2020-04-24 um 10 53 05" src="https://user-images.githubusercontent.com/39526001/80193955-f4f19980-8619-11ea-8b6d-125e7ff83ad2.png">

**Comment by andresilveirah** [comment]
@s-hintz I believe this can be fixed in construction of the message. In fact, all content displayed there comes from the message setup in the dashboard. Closing this issue for now and if you need more support we can bring this up in our slack channel.

**Comment by s-hintz** [comment]
I believe that have seen German texts for the buttons in your JSON, but English is displayed.
We will get soon get a new ID for the message, if there are still problems then I will inform you.

**Comment by s-hintz** [comment]
I still see English buttons in the message and an English text in the privacy manager.
