### ISSUE TITLE
[SPRING] The SDK does not return it own version number properly.

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#158]
We want to display the version number of each linked SDK in our debug menu in our apps.

But from this SDK we do not get the expected string "5.2.2".
We do get:

(lldb) po ConsentViewControllerVersionString
"**@(#)PROGRAM:ConsentViewController  PROJECT:Pods-1\n**"

(lldb) po ConsentViewControllerVersionNumber
**1**

**Comment by andresilveirah** [comment]
@vilasma do you think you can have a look at this? Please make sure it works for both Swift and Obj-C.

**Comment by vilasma** [comment]
Sure @andresilveirah..

**Comment by andresilveirah** [comment]
@s-hintz It seems that this is a known issues with Cocoapods. 

> looks like the issue is related to importing the library as a static library via CocoaPods. Since it's not a framework, the AWSPinpointVersionString is never populated. However, even importing it as a framework causes issues, since CocoaPods creates its own umbrella framework for each Pod, and populates it with an unexpected version value (See #1051). 
https://github.com/aws-amplify/aws-sdk-ios/issues/1050#issuecomment-431079828

Even though the comment above was not on Cocoapods repo, I've seen the same repeating on other famous Swift frameworks such as Alamofire, ReachabilitySwift, to name a few.

The solution proposed around the web is to get the version number from the `CFBundleShortVersionString` constant instead:
```swift
Bundle(for: GDPRConsentViewController.self).infoDictionary?["CFBundleShortVersionString"]
```

**Comment by s-hintz** [comment]
We are not using Cocoapods at all.
So this can not the cause of the problem.

**Comment by andresilveirah** [comment]
@s-hintz I should have elaborated further. The problem arises when a framework is imported by a project not using cocoapods. Only when using cocoapods, the `<pod name>VersionString` will get populated correctly.

**Comment by s-hintz** [comment]
OK. Thank you for clarification. So we will try the workaround for showing the version information in our debug menu.
