### ISSUE TITLE
[SPRING] Vendors are not visible in portrait mode

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#159]
It is not nice to the user, that he needs to rotate his device to see the vendor list in the privacy manager.

<img width="504" alt="Bildschirmfoto 2020-06-05 um 14 40 44" src="https://user-images.githubusercontent.com/39526001/83877499-ee872f00-a73a-11ea-86e4-f10fe72398fb.png">
<img width="882" alt="Bildschirmfoto 2020-06-05 um 14 40 49" src="https://user-images.githubusercontent.com/39526001/83877536-fc3cb480-a73a-11ea-8b17-c7427bd37867.png">

**Comment by andresilveirah** [comment]
Hi please report all layout issues on our Slack channel. Since this is web related content, there's nothing we can do from within the SDK.

**Comment by s-hintz** [comment]
Even if this will not be fixed in SDK but in some HTML, we need to have tool to track those bugs.
And GitHub is a central place for that.
Closing unfinished problems is not helpful.
