### ISSUE TITLE
[SPRING] Grey boxes while scrolling

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#160]
When I the privacy manager is touched a grey highlight is displayed. This is OK.
When the user moves his finger, a scroll view scrolls. This is also OK.
But the grey highlight does not scroll. This is not OK.
<img width="504" alt="Bildschirmfoto 2020-06-05 um 15 49 13" src="https://user-images.githubusercontent.com/39526001/83884182-d1eff480-a744-11ea-9e88-72f89a739cfc.png">
<img width="504" alt="Bildschirmfoto 2020-06-05 um 15 49 22" src="https://user-images.githubusercontent.com/39526001/83884194-d6b4a880-a744-11ea-9763-50dbb7f0c0cb.png">
<img width="504" alt="Bildschirmfoto 2020-06-05 um 15 49 43" src="https://user-images.githubusercontent.com/39526001/83884199-d7e5d580-a744-11ea-83ac-baad2e1bfd9d.png">

**Comment by andresilveirah** [comment]
@atanurdemirci I believe this is also something that should be fixed on the web side. Can you follow up with the web team?

**Comment by andresilveirah** [comment]
@atanurdemirci do you have an update for us?

**Comment by s-hintz** [comment]
It seems to be fixed.
