### ISSUE TITLE
[SPRING] Overlapping status bar in privacy manager

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#161]
See https://github.com/SourcePointUSA/ios-cmp-app/issues/160 for screenshots.

**Comment by andresilveirah** [comment]
@atanurdemirci are you able to reproduce this? I've created a [ticket](https://sourcepoint.atlassian.net/browse/SP-3810) to our web team but I'm not sure it was followed up.

**Comment by s-hintz** [comment]
It is still reproducible by clicking on a chevron.
![Simulator Screen Shot - iPhone 11 - 2020-08-18 at 16 58 08](https://user-images.githubusercontent.com/39526001/90529584-29163a80-e174-11ea-92e2-9156d2004916.png)

**Comment by s-hintz** [comment]
To solve the problem you can add four 0px constraints from the WKWebView to the safe area instead of the super view.

**Comment by jkuehne-spring** [comment]
@atanurdemirci  what´s the status here? We still see this issue which was communicated first at June-8. What´s the ETA for the fix?

**Comment by atanurdemirci** [comment]
@jkuehne-spring I was under the impression that we've added a new PM Template where this has been fixed... Is this still an issue?

**Comment by s-hintz** [comment]
The safe area is still not respected in the consent layer. Instead a top padding was implemented.
The notch overlaps the text.
The buttons have no padding.
The buttons are overlapping the text.

<img width="1047" alt="Bildschirmfoto 2020-10-23 um 14 39 39" src="https://user-images.githubusercontent.com/39526001/97005205-6addab80-153e-11eb-9ba6-b500a7a1d092.png">

And in the privacy manager a button touches the round corners of the device.
The home button overlaps the reject button.
The content and the back button are overlapping.

<img width="584" alt="Bildschirmfoto 2020-10-23 um 14 43 15" src="https://user-images.githubusercontent.com/39526001/97005265-8052d580-153e-11eb-8812-ab73d55df8ff.png">

![Simulator Screen Shot - iPhone 11 - 2020-10-23 at 14 42 52](https://user-images.githubusercontent.com/39526001/97005574-eb041100-153e-11eb-9d75-f81c7fdf756c.png)

**Comment by FSchanbacher** [comment]
this can be closed - mentioned issues are fixed or worked on in other tickets and initial problem is fixed by changing pm template.
for the consent layer in landscape, we might open a new issue - thx
