### ISSUE TITLE
[SPRING] Why is the privacy manager partly in English?

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#163]
Has this to be be fixed by SourcePoint or by us in the backend?

<img width="504" alt="Bildschirmfoto 2020-06-05 um 16 13 36" src="https://user-images.githubusercontent.com/39526001/83886807-df5aae00-a747-11ea-85ce-732898186d42.png">

**Comment by andresilveirah** [comment]
@atanurdemirci I believe there's some translation missing in their PM. Can you check? This is also something we can't fix via SDK but I'll keep it open until Atanur report back.

**Comment by atanurdemirci** [comment]
Hi s-hintz, this is a missing translation string in the sourcepoint ui. You can open the privacy manager, go to "Settings" and toggle "Purpose Content"

<img width="361" alt="Bildschirmfoto 2020-06-23 um 16 11 27" src="https://user-images.githubusercontent.com/5242987/85414411-5e374f80-b56c-11ea-9729-891217aaa42c.png">

**Comment by s-hintz** [comment]
So who is the person in charge of changing this?

**Comment by atanurdemirci** [comment]
Anyone with access to the ui can change that, I can change that for you if you provide the text

**Comment by andresilveirah** [comment]
@atanurdemirci was that addressed? If so, let's close the the issue.

**Comment by atanurdemirci** [comment]
Yes, this can be edited in the message builder... let's close it!
