### ISSUE TITLE
[SPRING] When I change the propertyName no GDPRNativeMessageViewController is shown.

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#164]
I changed the propertyName from GDPRPropertyName("BILD-NEWS-IOS") to GDPRPropertyName("BILD-IOS") and no message controller is shown.

If this name is unknown, I would expect to see a log message like "unknown propertyName".
Did I overlook something, or do you do no error handling?

**Comment by andresilveirah** [comment]
@s-hintz have you also changed the `propertyId` or were you just checking if you get an error when passing an inexistent property name?

**Comment by s-hintz** [comment]
I did not change the `propertyId`.
In our internal ticket for updating the CMP SDK, I was told also to update the **Cookie Layer ID**.
But I think there is no parameter to set it.
And I also noticed that the property name was different than before, so I tried to change it, but that did not work.

**Comment by andresilveirah** [comment]
@s-hintz I'm not sure where that `Cookie Layer ID` is coming from. 

By looking at your account, I can't find any property with the name `BILD-IOS`. But I do find `BILD-NEWS-IOS`. 

If you provide an property name that doesn't exit, but the property id does, there'll be no error. The SDK will behave simply as if there was no message to display. I agree it'd be helpful to have an error message indicating the property name wasn't found, but that's not on our roadmap yet.

**Comment by s-hintz** [comment]
Thank You.

**Comment by s-hintz** [comment]
So you have no error handling on your road map?
