### ISSUE TITLE
[SPRING] backend configuration is broken for BILD-NEWS-IOS native message

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#187]
https://analytics.sourcepoint.com/dialogue/native-message-gdpr?site_id=5593

<img width="1446" alt="Bildschirmfoto 2020-06-12 um 12 51 00" src="https://user-images.githubusercontent.com/39526001/84495479-86d96280-acab-11ea-88bb-39cacbbc1978.png">

**Comment by atanurdemirci** [comment]
Hi s-hintz, I think the only problem here is that the native message can not be rendered in oder to create a  thumbnail. Are you experiencing any functional issues?

**Comment by s-hintz** [comment]
Yes. This is how it looks in our app:

![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-03-27 at 08 42 34](https://user-images.githubusercontent.com/39526001/85414670-b1a99d80-b56c-11ea-800e-e83a6a66afe1.png)

**Comment by andresilveirah** [comment]
Gentlemen @atanurdemirci @s-hintz I'm not sure what's needed from the SDK in this issue. Can we close it?

**Comment by andresilveirah** [comment]
@s-hintz closing this issue as I'm not sure what needs to be done here. Let me know if we should re-open it with more context.
