### ISSUE TITLE
[SPRING] Privacy Layer delegate method is not called if we called loadNativeMessage

### ISSUE THREAD

**Issue by toupper** [SourcePointUSA/ios-cmp-app#202]
In the case when we want to show the privacy layer via a deeplink, we have the following process:
1-. Call Privacy Layer Deeplink URL from Safari
2-. App opens, `loadNativeMessage` is called to verify the user consent, as always happens when starting the app
3-. `loadPrivacyManager()` is called to show the privacy manager as demanded by the deeplink.
4-. `onConsentReady` delegate method is called
5-. EXPECTED, NOT HAPPENING `gdprConsentUIWillShow` delegate method is called, so we can react and show the `UIViewController` 
The onError delegate method is not called either.

The privacy layer showing process is executed correctly when we do not call to load the native message.

**Comment by andresilveirah** [comment]
@toupper there are many moving parts here, I'll reach out to you via slack because I think it'll be the most efficient in finding out how to reproduce.

**Comment by andresilveirah** [comment]
Señor @toupper , have you managed to work pass this issue?

**Comment by toupper** [comment]
Si, senhor @andresilveirah We can close it for now. As a improvement i would suggest that we call the delegate method `onError` if the operation was blocked, and/or that we expose publicaly the loading status so we can check in advance.

**Comment by andresilveirah** [comment]
Makes sense @toupper . I wouldn't go as far as calling `onError` because that's likely to disturb our clients' implementations. But making the loading status publicly available is an easy change.
