### ISSUE TITLE
[SPRING] Overlapping status bar in the message web view

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#216]
The iOS safe area in not respected.

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-27 at 15 40 02](https://user-images.githubusercontent.com/39526001/88550644-30896e80-d022-11ea-992c-45012874be38.png)

**Comment by jkuehne-spring** [comment]
@atanurdemirci what´s the ETA for the fix?

**Comment by FSchanbacher** [comment]
can be closed - with the new templates this is no longer an issue
