### ISSUE TITLE
Crash at PropertyName

### ISSUE THREAD

**Issue by iOSDevFin** [SourcePointUSA/ios-cmp-app#223]
The SDK crashes when we use a property name that contains special characters. During setup in the dashboard, special characters are allowed when we create a property name. There is n inconsistency between the dashboard and SDK.

<img width="970" alt="Bildschirmfoto 2020-08-07 um 11 04 03" src="https://user-images.githubusercontent.com/5556361/89629210-bb2d6180-d89d-11ea-849c-8511b393afd8.png">

**Comment by andresilveirah** [comment]
Hi Maik @iOSDevFin . Thank you for flagging this up. Indeed there's a mismatch in our portal validation. Even though you're able to create properties with underscores `_`, our internal APIs won't work as expected. 
I've created a ticket and assigned to my backend colleagues but the fastest solution for you would be using another name (which, I understand isn't great...).
