### ISSUE TITLE
[SPRING] CMP Error handling for Consent Layer

### ISSUE THREAD

**Issue by pBoelck** [SourcePointUSA/ios-cmp-app#238]
**Describe the bug**
While the Consent-Layer is visible and then _all cmp-calls_ are blocked. Click on _EINSTELLUNGEN_ (Privacy Manager).
Result: nothing happens - Consent layer still displayed, no alert
Should: Consent-Layer should disappear and onError function is called.

All CMP-calls are:
- wrapper-api.sp-prod.net
- sourcepoint.mgr.consensu.org
- notice.sp-prod.net
- cdn.privacy-mgmt.com
- d2p3zdq8vjvnxd.cloudfront.net

It also happens if only the single url is blocked:
- notice.sp-prod.net

About your campaign (please complete the following information):

Account Id: 75
Property Id: 5593
Property Name: "BILD-NEWS-IOS"
Campaign Env: .Public
Targeting Params: ["native": "true"]
AuthId: nil
** About your environment **

SDK version: 5.2.8
Device: iPhone 11
OS: iOS 13

**Comment by atanurdemirci** [comment]
Hi @pBoelck Thanks for reporting, we'll take a look!

**Comment by andresilveirah** [comment]
@pBoelck are you using the native (`.loadNativeMessage`) or web (`.loadMessage`) message?

**Comment by pBoelck** [comment]
We use the `loadMessage(forAuthId authId: String?) `function

**Comment by andresilveirah** [comment]
There were a few changes to our front end and I'm no longer to reproduce the issue with our Example app. Do you mind giving it a try on your app and let me know if the `onError` callback is called?

**Comment by FSchanbacher** [comment]
Just checked this again and there's still the same problem appearing when blocking e.g. the url _notice.sp-prod.net_ while the consent layer is displayed - you click on 'Einstellungen oder ablehnen' + nothing happens (no alert, no pm, still displayed consent layer) - in this case, the user is forced to click 'Alle akzeptieren' to use the app which is not an option (and not legally compliant)
console output is only: 
[CMP] Show privacy manager

**Comment by andresilveirah** [comment]
@FSchanbacher @pBoelck I've tried reproducing that using our example app but no luck. Here are the steps I followed:
1. Fresh install - the consent message shows up
2. Block urls* using Charles
3. Click on _Einstellung oder ablehnen_
4. The `onError` is called.

*The list of urls I blocked were
<img width="542" alt="Screenshot 2020-10-05 at 15 31 50" src="https://user-images.githubusercontent.com/228650/95085745-ec9c9f00-071f-11eb-8894-982f7f9cad3b.png">

**Comment by FSchanbacher** [comment]
I did exactly the same :) 
we'll look into that again and get back here for feedback

**Comment by pBoelck** [comment]
@andresilveirah 
I can reproduce the problem with your step-by-step instructions.
1. Fresh install - the consent message shows up
2. "BLock URLs* using Charles (I'm using the same blocklist entries like you.)
3. Click on "Einstellungen oder Ablehnen"

Nothing happens. The Debugger doesn't jump in the onError delegate function.

We are using the version "5.2.8" of "SourcePointUSA/ios-cmp-app"

*The list of URLs I blocked were
![image](https://user-images.githubusercontent.com/52406129/95199857-c806fc80-07dd-11eb-93ca-a0552e5749ae.png)

**Comment by FSchanbacher** [comment]
the problem here is not only, that we don't get an alert/error message displayed but that the consent layer stays at it's position and the user's only option to go on and use the app in that case is to tab 'Alle akzeptieren' which is not legally compliant as we literally force the users to accept everything in order to use the product (for example when only the notice.sp-prod.net-call is failing while consent layer is displayed)

**Comment by pBoelck** [comment]
Good morning,

I can reproduce the behavior we described with your example app. I block the calls listed above and do not get an error message when I try to call the Privacy Manager via the Consent layer or the Consent layer.

I first had to read how to set up the iOS Simulator for Charles. The following page has helped me: https://www.detroitlabs.com/blog/2018/05/01/how-to-set-up-charles-proxy-for-an-ios-simulator/

I have recorded the behavior described by us with a screen recording as a video and attach the [link](https://moveoffice-my.sharepoint.com/:v:/g/personal/pascal_boelck_axelspringer_com/EQJxrVxPUAFJr2TnTvGIQOYBGP_PlTWQdybOJIOZY6su3w?e=fPPnXq) here.
**It expires on Friday, Nov 13, 2020.**

**Comment by andresilveirah** [comment]
Hi @pBoelck thank you for giving our Example app a try. Let me go through the article you mentioned and I already downloaded the screen recording as well. 
I'll probably reach out to you via Slack to reduce the feedback loop. Ideally I'd like to have a call about this issue today still if you're available later.

**Comment by andresilveirah** [comment]
@pBoelck can you give pod version `5.2.10` a try? It should now trigger the `onError` callback when you block the URLs using Charles.

**Comment by FSchanbacher** [comment]
this works fine now after implementing SDK 5.2.10 into our app
