### ISSUE TITLE
[SPRING] CMP Error Handling for Click on Social Placeholder in Articles

### ISSUE THREAD

**Issue by pBoelck** [SourcePointUSA/ios-cmp-app#239]
**Describe the bug**
We block the some single urls and call the function: _consentViewController?.customConsentTo(vendors:, categories:, legIntCategories:)_ to activate the social consent.
Result: social element gets displayed + alert displayed
Should: social element gets displayed + no alert

Every time if we block one or more of these urls:
- sourcepoint.mgr.consensu.org
- notice.sp-prod.net
- cdn.privacy-mgmt.com
- d2p3zdq8vjvnxd.cloudfront.net

About your campaign (please complete the following information):
Account Id: 75
Property Id: 5593
Property Name: "BILD-NEWS-IOS"
Campaign Env: .Public
Targeting Params: ["native": "true"]
AuthId: nil
** About your environment **

SDK version: 5.2.8
Device: iPhone 11
OS: iOS 13

**Comment by FSchanbacher** [comment]
this issue can be closed - we adapted our code and it now works as expected
