### ISSUE TITLE
[SPRING/NMT] Back-button in 'Drittanbieter' section overlaps with content while scrolling

### ISSUE THREAD

**Issue by FSchanbacher** [SourcePointUSA/ios-cmp-app#249]
**Describe the bug**
When entering the 'Drittanbieter' section in privacy manager (after fix for overlapping status bar / safe area) you can scroll through the different vendors. While doing so the back button stays fixed and gets overlapped by other content (see video attached). 

 - Account Id: 75
 - Property Id 5593
 - Property Name BILD-NEWS-IOS
 - PrivacyManager Id: 134100

** About your environment **
 - SDK version: 5.2.8
 - Device: iPHone / iPad
 - OS: all

** To Reproduce**
1. Go to privacy manager
2. Tap on _Drittanbieter_
3. Scroll down 

**Expected behavior**
back button disappears while scrolling or does not overlap with other content

![back-button-overlapping](https://user-images.githubusercontent.com/39551150/96122501-e1046180-0ef1-11eb-963d-16c97a4fa9b3.png)

**Comment by haerju** [comment]
@FSchanbacher @andresilveirah This should be resolved and the ticket can be closed.

**Comment by FSchanbacher** [comment]
this also happens in the legitimate interest section - can you fix it there too please?
for 3rd party section it works fine now - thx

**Comment by haerju** [comment]
@FSchanbacher  My bad, this should be fixed now as well. @andresilveirah you can close this ticket.

**Comment by FSchanbacher** [comment]
@haerju 
great - works fine there too now - thank you
