### ISSUE TITLE
[SPRING/NMT] AUS + AN in sub-categories not placed correctly

### ISSUE THREAD

**Issue by FSchanbacher** [SourcePointUSA/ios-cmp-app#251]
Opening sub-categories for vendors in the Drittanbieter section shows that the words AN and AUS in the opt-in/out-switches aren't placed correctly (too far left/right - see screenshots)

    Account Id: 75
    Property Id 5593
    Property Name BILD-NEWS-IOS
    PrivacyManager Id: 134100

1. Go to privacy manager
2. Tap on 'Drittanbieter'
3. open sub-category with opt-in button

**Expected behavior**
The placement of the words inside the switches should be the same as in the main categories (centered).

![aus](https://user-images.githubusercontent.com/39551150/96123534-4016a600-0ef3-11eb-993f-198d466eed6f.png)
![an](https://user-images.githubusercontent.com/39551150/96123540-4147d300-0ef3-11eb-8872-05a378dd3a21.png)

**Comment by haerju** [comment]
@FSchanbacher @andresilveirah This shoudl be resolved and ticket can be closed.

**Comment by FSchanbacher** [comment]
works fine now - thx
