### ISSUE TITLE
[SPRING/NMT] performance issues while scrolling through Drittanbieter section

### ISSUE THREAD

**Issue by FSchanbacher** [SourcePointUSA/ios-cmp-app#252]
**Describe the bug**
When scrolling through the different vendors in the Drittanbieter section (after fix for overlapping status bar / safe area) it is not possible to scroll fluently (especially when scrolling up again).

    Account Id: 75
    Property Id 5593
    Property Name BILD-NEWS-IOS
    PrivacyManager Id: 134100

** To Reproduce**
1. Go to privacy manager
2. Tap on _Drittanbieter_
3. Scroll down and up

**Expected behavior**
Fluent scrolling through vendors should be given

**Additional context**
It is worse when scrolling up again than when scrolling down.

**Comment by haerju** [comment]
@FSchanbacher This issue seems to be app specific. I am not able to reproduce with our Test App for the BILD-NEWS-IOS Vendor List and I am also not seeing this issue when using other apps.

**Comment by FSchanbacher** [comment]
I also can no longer reproduce it - I'll close it - thx
