### ISSUE TITLE
[NMT] problems with consent layer in landscape

### ISSUE THREAD

**Issue by FSchanbacher** [SourcePointUSA/ios-cmp-app#255]
First Layer (Version “1st Layer MOBIL APP 10-2020”, tested in BILD News iOS)
We are seeing an issue with the buttons in landscape mode on the first layer as well (see images below).

Account Id: 75
Property Id 5593
Property Name BILD-NEWS-IOS
PrivacyManager Id: 134100

1. start app on an iPhone (consent layer is visible)
2. turn device to landscape

![plus-device](https://user-images.githubusercontent.com/39551150/96583591-3b7c3400-12dd-11eb-9c14-1a80b03c1e44.png)
![iphone-x](https://user-images.githubusercontent.com/39551150/96583600-3f0fbb00-12dd-11eb-80a2-4f2a11e5ccd6.png)

**Comment by dsimetchiev** [comment]
![device-2020-10-20-142613](https://user-images.githubusercontent.com/38256166/96585864-72a01480-12e0-11eb-8f12-58c881348dbc.png)
Also in Android, here on Samsung Galaxy A5 with Android 6.0.1

**Comment by haerju** [comment]
@FSchanbacher I moved the buttons to horrizontal aligment for displays > 480px and set a min-width for the div wrapper that holds the buttons. Unfortunately I our Meta App doesn't rotate on iphones when tested with Xcode, so please let me know if any additional adjustments are needed. In any event, any remaining adjustments should be very minor.

**Comment by FSchanbacher** [comment]
looks fine - thx
