### ISSUE TITLE
[NMT] consent layer not correctly displayed on devices with notch in landscape

### ISSUE THREAD

**Issue by FSchanbacher** [SourcePointUSA/ios-cmp-app#258]
**description**
Putting a device with a notch into landscape while Consent/Cookie Layer is displayed hides content behind it (overlaps with text, arrows, part of buttons)

**campaign**
Account Id: 75
Property Id 5593
Property Name BILD-NEWS-IOS
PrivacyManager Id: 134100

**environment**
- SDK version 5.2.10
- iPhones with Notch (X, 11, 12)

**steps to reproduce**
1. start app initially
2. put device to landscape

**expected behavior**
All content displayed within consent layer should be clearly readable in all orientations on all devices

**screenshot**
![notch-issue](https://user-images.githubusercontent.com/39551150/97586066-22206980-19fa-11eb-92f8-41b28111641e.jpeg)

**Comment by haerju** [comment]
@FSchanbacher This issue should be solved with a new version of the Privacy Manager that is currently in staging for the Bild app. Once your team updates the campaign this issue should disappear.

@andresilveirah this issue can be resolved.
