### ISSUE TITLE
[NMT] Latest version 5.3.4 does not compile

### ISSUE THREAD

**Issue by matance** [SourcePointUSA/ios-cmp-app#281]
**Describe the bug**
The latest version 5.3.4 does not compile. I am using Xcode 12.4. 
The error is in `PDeviceManager` : `Cannot find 'UIDevice' in scope`.
I think there is an `import UIKit` is missing.

**About your environment**
 - SDK version: 5.3.4

**To Reproduce**
1. Try to compile a project with the SDK version 5.3.4
2. See error

**Expected behavior**
Newest SDK should compile

**Comment by s-hintz** [comment]
We are using Swift Packages. Version 5.3.3 did not have this problem.
By adding the import, the problem would be solved:

<img width="535" alt="Bildschirmfoto 2021-01-29 um 10 54 13" src="https://user-images.githubusercontent.com/39526001/106262555-83d3b800-6223-11eb-964a-7556d57a7d90.png">

**Comment by andresilveirah** [comment]
Hi @matance thank you for reporting this issue and @s-hintz thanks for the tip. Are you both using SPM?
The solution seems straight forward, I just don't understand how this issue slipped through the build/test process.

**Comment by s-hintz** [comment]
Yes we are using SPM.

**Comment by clausjoergensen** [comment]
Same issue here, with SPM.

> Hi @matance thank you for reporting this issue and @s-hintz thanks for the tip. Are you both using SPM?
> The solution seems straight forward, I just don't understand how this issue slipped through the build/test process.

You need to try and build the project from the Package.swift, your regular Xcode project will not do. If you build the code from a project that statically links UIKit (and/or Foundation) you'll not see errors like this.

**Comment by matance** [comment]
Any news on this issue @andresilveirah ?

**Comment by andresilveirah** [comment]
@matance yes. It's taking us a bit longer than expected to setup our build/test process to catch issues like this. The good news is, @vilasma is going to release it by today 🎉

**Comment by andresilveirah** [comment]
@matance @clausjoergensen we just released version `5.3.5` can you give it a try and let me know if it solved the issue for you? 
We added a few different targets on our CI to make sure we're building with the different dependency managers from now on.

**Comment by matance** [comment]
@andresilveirah : version 5.3.5 solves the SPM issue 👍
