### ISSUE TITLE
Objective-C: Property 'gdpr' not found on object of type 'SPUserData *'

### ISSUE THREAD

**Issue by MacMark** [SourcePointUSA/ios-cmp-app#295]
**Describe the bug**
The attribute gdpr is not found in SPUserData using Objective-C

** About your environment **
 - SDK version 6.0.1
 - OS: iOS 14.5

** To Reproduce**

In
```
- (void)onConsentReadyWithUserData:(SPUserData *)userData {
 SPGDPRConsent *userConsent = userData.gdpr; // Compiler Error: Property 'gdpr' not found on object of type 'SPUserData *'
}
```

**Expected behavior**
No compiler error

**Comment by andresilveirah** [comment]
@MacMark thank you for reporting this issue. We started working on a fix and you should receive an update soon.

**Comment by andresilveirah** [comment]
@MacMark version `6.0.2` fixes this issue. You can access both GDPR and CCPA consents on Objc by:
```Objc
    NSLog(@"GDPR Applies: %d", userData.objcGDPRApplies);
    NSLog(@"GDPR: %@", userData.objcGDPRConsents);
    NSLog(@"CCPA Applies: %d", userData.objcCCPAApplies);
    NSLog(@"CCPA: %@", userData.objcCCPAConsents);
```
