### ISSUE TITLE
completionHandler of customConsent is not called

### ISSUE THREAD

**Issue by marcelklinek** [SourcePointUSA/ios-cmp-app#296]
**Describe the bug**
When I submit custom consent using `consentViewController.customConsentTo()`, the completionHandler is never called, even though the request goes through and server responds with 200.

** About your environment **
 - SDK version 5.3.6
 - Device: iPhone XR
 - OS:  iOS 14.4.2

** To Reproduce**
1. Go to Privacy Manager
2. Tap on Accept all
3. Send customConsent
4. No callback

Debugging reveals that `client.post` does not return in `SourcePointClient.swift`

<img width="992" alt="Snímek obrazovky 2021-05-12 v 17 58 52" src="https://user-images.githubusercontent.com/1367467/118006704-c7be7900-b34b-11eb-8e90-8edd2f3e909c.png">

**Expected behavior**
I expect `completionHandler` which I pass to `customConsentTo` to be called.

```
consentViewController.customConsentTo(vendors: customConsentData.vendors, categories: customConsentData.categories, legIntCategories: customConsentData.legIntCategories, completionHandler: completionHandler)
```

**Additional context**
I saw there is a new version out and upgraded, unfortunately with the new version I get a different problem

**Comment by marcelklinek** [comment]
Oops, my bad, forgot to keep a reference to ConsentViewController. Sorry for false alarm!

**Comment by andresilveirah** [comment]
Ha! Thank you for letting us know @marcelklinek . I was trying to reproduce this issue in this exact moment 😅

**Comment by marcelklinek** [comment]
In the new version I can’t seem to submit a consent — which is a prerequisite for sending a `customConsent`. After upgrade to v6 of the library, when giving consent with privacy manager, the API returns error 500 and reports
`Localstate does not have gdpr attribute.`

**Comment by marcelklinek** [comment]
Thanks for looking into the original issue, appreciate it! I am sorry for wasting your time.
We will for now stay on v5, but will probably look again into upgrading to v6 soon.

**Comment by andresilveirah** [comment]
Hi @marcelklinek I appreciate you taking the time to report the issue either way. The `customConsent` is a tricky feature. It's meant to be used only after `.loadMessage` has been called at least once. Was that your case?
