### ISSUE TITLE
onSPUIReady not being called, SDK dies silently

### ISSUE THREAD

**Issue by notboring** [SourcePointUSA/ios-cmp-app#305]
**Describe the bug**
After updating the SDK to version 6.02 from the latest 5.x version the SDK stopped displaying a popup when using our companies access data. The culprit seems to be onSPUIReady. According to the documentation onSPUIReady should be triggered after calling loadMessage() but it never gets triggered. The SDK just silently dies without error or any other kind of feedback.

**About your campaign (please complete the following information):**
I don't want to post these in public. Feel free to contact me directly for the data.

** About your environment **
 - 6.02
 - iPad 12,9" 2020; iPhone XS Max
 - iOS: 14.5.1

** To Reproduce**
1. Use example code posted here
2. Use our applications data instead of the example data
3. Start the application

**Expected behavior**
onSPUIReady should be triggered after calling loadMessage().

**Additional context**
When using the "mobile.multicampaign.demo" configuration from the example our code works. As soon as we use the confguration data of my client it just dies silently.

**Comment by andresilveirah** [comment]
Hi @notboring (cool username btw), the behaviour you described is expected. The new version of the SDK is meant to be used with the new kind of campaign (multi-campaigns). I'm talking to my colleague who's responsible for your account and we'll ping you shortly about it. Meanwhile, I'll keep this issue open until we have new campaigns for you.

**Comment by notboring** [comment]
Thanks, that already helps me a lot. I will contact the person responsible for setting up these things. I switched back to 5.X for now so we can release our new app version.
