### ISSUE TITLE
Documentation is wrong

### ISSUE THREAD

**Issue by dungi** [SourcePointUSA/ios-cmp-app#324]
**Describe the bug**

Documentation for SPDelegate is:

```
    func onConsentReady(consents: SPUserData) {
        print("onConsentReady:", consents)
    }

```

but should be

```
    func onConsentReady(userData: SPUserData) {
        print("onConsentReady:", consents)
    }

```

I always thought I did something wrong...

**About your campaign (please complete the following information):**
 - Account Id
 - Property Id
 - Property Name
 - Campaign Env
 - PrivacyManager Id
 - Targeting Params (if any)
 - AuthId (if any)

** About your environment **
 - SDK version

** To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by andresilveirah** [comment]
Hi @dungi thank you for taking the time to report this issue. I just committed a fix and will merge it to `develop` / `master` soon.
