### ISSUE TITLE
Button action invoking error delegate method

### ISSUE THREAD

**Issue by aatanac** [SourcePointUSA/ios-cmp-app#325]
**Describe the bug**
While pressing button with redirect url(tested with website url and custom url scheme) getting error "Could not parse the event: onAction with body: {"consentLanguage": "DE","type": 5,"id": "4610094"}"
With debugging found out that action is failing to parse type 5 because that type does not exist in SPActionType enum.
Tried to update SDK with Cocoapods 6.1.4 -> 6.1.5, not possible:

`[!] CocoaPods could not find compatible versions for pod "ConsentViewController":
  In Podfile:
    ConsentViewController (= 6.1.5)

None of your spec sources contain a spec satisfying the dependency: ConsentViewController (= 6.1.5).
`

**About your campaign (please complete the following information):**
 - Account Id: 1748
 - Property Id: 17526
 - Property Name: DeinUpdate-iOS
 - Campaign Env: Public
 - PrivacyManager Id
 - Targeting Params (if any)
 - AuthId (if any)

** About your environment **
 - SDK version - 6.1.4
 - Device: iPhone X
 - OS: 14.6

**Expected behavior**
After button click opening call to `SPDelegate` method
`func onAction(_ action: SPAction, from controller: SPMessageViewController) {
`

**Additional context**
Can you help please with this issue? Not sure if I am doing something wrong. Dismiss actions are working well but with redirect url is failing.

**Comment by andresilveirah** [comment]
Hi @aatanac you are not doing anything wrong. The `Redirect` action type is relatively new and we didn't have the time to add support to it in the SDK. We are going to add support to it (but unfortunately I don't have the estimated date). The alternative, for now, is to use a regular link within the message instead of a `Redirect` action/button. 
I'll keep this issue open until I have more information about the implementation of this action.

**Comment by aatanac** [comment]
Hi @andresilveirah ,
Thank you for quick response. 
Can you point me if there is option for button that could be used to open part of app, navigate to different screen?
We would like to present screen over `GenericWebMessageViewController` without dismissing it

**Comment by andresilveirah** [comment]
@aatanac for now, I believe you'd have to add a text element, add a link inside this text element and style it as a button. The link should be a deep-link to your own app. When pressed, your app should have logic to handle it (by presenting another view controller, for example). 
Just out of curiosity, what would you like to present on top of the consent screen?

**Comment by aatanac** [comment]
@andresilveirah  Tnx for suggestion.
We would show Privacy policy, Contact and Subscription screens. Will try with deeplink and get back to you if there are additional problems

**Comment by aatanac** [comment]
@andresilveirah  Tested text element styled and used as link. If we setup url of website it opens browser, works fine, but deeplink does not work, it is not calling designated method in `AppDelegate`. 
Same deepLink is tested with `UIApplication.openUrl` method and also in separate project with wkWebview where its caught in `webView(_ webView: WKWebView, decidePolicyFor navigationAction: WKNavigationAction, decisionHandler: @escaping (WKNavigationActionPolicy) -> Void)`. So from my understanding we would need pointer to WKWebView property to setup delegate or in other case we won't be able to catch action from deeplink. Please correct me if I am wrong and point me to right solution with possible example in the code.

**Comment by aatanac** [comment]
Hi @andresilveirah 
Is there any progress with this issue?

**Comment by andresilveirah** [comment]
@aatanac this since long been fixed, sorry for not getting back to you.
