### ISSUE TITLE
Carthage no longer able to build

### ISSUE THREAD

**Issue by icedice** [SourcePointUSA/ios-cmp-app#333]
**Describe the bug**
When updating from 6.0.3 to 6.1.6 carthage is no longer able to build, instead I now see this error:

*** Skipped building ios-cmp-app due to the error:
Dependency "ios-cmp-app" has no shared framework schemes for any of the platforms: iOS

** About your environment **
 - SDK version: 6.1.6
 - Device: -
 - OS: -

**Expected behavior**
The framework should build without errors

**Comment by andresilveirah** [comment]
Hi @icedice thank you for taking the time to report this issue. We're investigating how this passed our CI setup. You should expect a fix early next week.

**Comment by icedice** [comment]
Working great. Thank you.
