### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException

### ISSUE THREAD

**Issue by icedice** [SourcePointUSA/ios-cmp-app#340]
**Describe the bug**
We are seing a few crashes related to the SDK lately (see the screenshot)
Is it possible for `onSPUIReady` to get called multiple times with the same `SPMessageViewController` instance? Why would this happen and how should we handle the situation?

** About your environment **
 - SDK version: 6.1.6

** To Reproduce**
Have not been able to reproduce.

**Expected behavior**
Was expecting `onSPUIReady` to only be called once (at least only once per `SPMessageViewController` instance)

**Screenshots**
<img width="1294" alt="Screenshot 2021-08-31 at 12 29 29" src="https://user-images.githubusercontent.com/5115869/131488640-af1286b2-57ad-4da1-99cf-b3bc3047de21.png">

**Comment by dungi** [comment]
Thanks for the info. Our app also crashes with 6.x.0 the last weeks.

**Comment by andresilveirah** [comment]
@dungi without logs and a list of steps to reproduce the problem, it'd be hard for us to track this issue down. I'm closing it for the time being.
