### ISSUE TITLE
Support for SPM 

### ISSUE THREAD

**Issue by integer256** [SourcePointUSA/ios-cmp-app#348]
**Describe the bug**
We are currently migrating to SPM and we will stop using Carthage. Would it be possible to integrate support for SPM?

**About your campaign (please complete the following information):**
SoundCloud

**Comment by andresilveirah** [comment]
Hi @integer256 , yes. You can use SPM to integrate our SDK into your project. All you need to do is setup your XCode project to fetch the latest version (or the version you already use) from https://github.com/SourcePointUSA/ios-cmp-app.git
