### ISSUE TITLE
Version 6.4.0 doesn't build

### ISSUE THREAD

**Issue by dungi** [SourcePointUSA/ios-cmp-app#359]
If I download Version 6.4.0 through SPM and try to build the app, the app failed to build.

Error:

`ConsentViewController/Classes/Constants.swift:29:53: cannot find type 'UIColor' in scope`

Need to import UIKit to this file.

**Comment by andresilveirah** [comment]
@dungi thank you for reporting this issue. We're working on a fix and it should be released today. I'll ping you once it's out.

**Comment by dungi** [comment]
I see there is an update. I will try tommorow and give feedback. I will close this issue, when it works.

**Comment by andresilveirah** [comment]
Thanks @dungi , let me know if it works for you.
