### ISSUE TITLE
Layout Issues

### ISSUE THREAD

**Issue by pwallrich** [SourcePointUSA/ios-cmp-app#36]
The Webview is not layed out as expected. It doesn't respect the safe area but displays fullscreen:

<img width="420" alt="Screenshot 2019-06-06 at 09 54 32" src="https://user-images.githubusercontent.com/13999931/59016354-5877aa80-8841-11e9-9d44-a97c8689e450.png">

**Comment by andresilveirah** [comment]
Hi @pwallrich thank you for reporting this issue. It's a known issue already and it's being worked on. Luckily for us native developers, this is not a SDK related problem but rather coming from the CSS layout. I'll let you know when it's solved.

**Comment by andresilveirah** [comment]
Hi @pwallrich was this issue resolved for you?
