### ISSUE TITLE
ViewController does not conform to SPDelegate

### ISSUE THREAD

**Issue by Iikeli** [SourcePointUSA/ios-cmp-app#395]
**Describe the bug**
When copying the example from README.md, the `extension ConsentVC: SPDelegate { ... }` does not conform to SPDelegate.

** About your environment **
 - SDK version: 6.7.0
 - Device: Xcode 14.1
 - OS: macOS Venture 13.0

** To Reproduce**
1. Copy the example code from `README.md`
2. Build
3. See error

**Expected behavior**
The code should build without errors.

**Comment by Iikeli** [comment]
(there is also additional errors in the `README.md` that I addressed in #394 )

**Comment by andresilveirah** [comment]
Well, that's a bit delayed 😅 But since #394 is merged, I believe we can close this issue. Thank you @Iikeli
