### ISSUE TITLE
SPDateCreated.swift - Line 32

### ISSUE THREAD

**Issue by dynaheirbe** [SourcePointUSA/ios-cmp-app#416]
Crashes at SPDateCreated.swift - Line 32  are locking users out of our application.
I see the date being force unwrapped which appears to be an inappropriate assumption given it is a throwing method❗️

**Comment by dynaheirbe** [comment]
Version 7.0.1

**Comment by andresilveirah** [comment]
Hi @dynaheirbe thank you for reporting this issue. I see our linting was faulty and didn't report that force unwrapping on our CI. We'll work to fix both the linting and remove the forced unwrapping. I'll ping you here once the release is out.

**Comment by dynaheirbe** [comment]
Thank you very much

**Comment by andresilveirah** [comment]
@dynaheirbe we just released version 7.0.2 of the SDK. Removing virtually all forced unwraps from the SDK (🎉 ). 
Do you mind giving it a try and let us know if you notice the same issue happening again?
