### ISSUE TITLE
Source Point 7 calls onSPFinished without onSPUIReady in iOS 14.0.1

### ISSUE THREAD

**Issue by dungi** [SourcePointUSA/ios-cmp-app#418]
**Describe the bug**
Source Point 7 calls onSPFinished without onSPUIReady

**About your campaign (please complete the following information):**
 - Account Id 1281
 - Property Id 18146
 - Property Name app.ln
 - Campaign Env Stage
 - PrivacyManager Id
 - Targeting Params (if any)
 - AuthId (if any)

** About your environment **
 - SDK version 7.0.2
 - Device: [e.g. iPhone6] iPhone 8 Plus
 - OS: [e.g. iOS8.1] 14.0.1 & 14.2

** To Reproduce**
1. Start App
2. CMP Dialog doesn't open
3. onSPFinished will be called

**Expected behavior**

CMP Dialog should be opened, before onSPFinished is called

**Screenshots**

**Additional context**

**Comment by atanurdemirci** [comment]
@dungi this is a configuration issue. PropertyId doesn't match with the PropertName you're using. The id you're using belongs to  app.waz-online.de.

**Comment by dungi** [comment]
Yes, propertyID was wrong. But the bug is still the same. CMP doesn't appear in iOS 14.4 or older. On newer OSes it works.

**Comment by dungi** [comment]
@atanurdemirci can you reopen this issue?

**Comment by dungi** [comment]
Going back to Version 6 of this Framework, fixed the issue for now.
