### ISSUE TITLE
The method form the readme does not exist

### ISSUE THREAD

**Issue by philipheinser** [SourcePointUSA/ios-cmp-app#485]
The following method mentioned in the readme as 5 easy steps does not exist:

```
SPCampaign *campaign = [[SPCampaign alloc] initWithTargetingParams: [NSDictionary dictionary]];
```
<img width="526" alt="Screenshot 2023-08-26 at 17 23 37" src="https://github.com/SourcePointUSA/ios-cmp-app/assets/3705499/786464a3-7491-4ec0-a20d-af778ce3d012">

**Comment by andresilveirah** [comment]
Hey @philipheinser , sorry for the inconvenience. We've added a few optional parameters to the Swift interface and forgot to update the readme with the correct method signature for Obj-C:

```objc
    SPCampaign *campaign = [[SPCampaign alloc]
                            initWithTargetingParams: [NSDictionary dictionary]
                            groupPmId: NULL // or the id of your group pm
                            gppConfig: NULL]; // or an instance of SPGPPConfig
```

I'm going to update the README in a second.

**Comment by philipheinser** [comment]
@andresilveirah I set the params to null seams to work they where marked as non null.
