### ISSUE TITLE
Xcode 15 toolchain issue 

### ISSUE THREAD

**Issue by rpitting** [SourcePointUSA/ios-cmp-app#488]
**Describe the bug**
I integrated the SDK via linked Framework as I need to support both iOS and tvOS, which the SPM unfortunately does not.

When I compile the app in Xcode 15 beta 8, I get the following error:

`Failed to build module 'ConsentViewController'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)', while this compiler is 'Apple Swift version 5.9 (swiftlang-5.9.0.128.106 clang-1500.0.40.1)'). Please select a toolchain which matches the SDK.`

I think this also happens because I cannot integrate the SDK via SPM.

When can you provide a version compatible with Xcode 15/iOS 17/tvOS 17?

** About your environment **
 - SDK version 7.3.0
 - Device: tvOS simulator
 - OS: tvOS 17

**Comment by andresilveirah** [comment]
@rpitting we just released version `7.4.2` with support to tvOS via SPM. Can you give it a try and let me know if the issue is solved for you? For the record, I'm able to build the project using XCode 15.0.1, iOS / tvOS 17.
