### ISSUE TITLE
[NMT] onAction is not triggered on "Einstellungen oder ablehnen"

### ISSUE THREAD

**Issue by timdolenko** [SourcePointUSA/ios-cmp-app#493]
**Describe the bug**
We need to track when user selects "Einstellungen oder ablehnen" ("Settings or reject"), on the consent screen.

**Screenshots**
<img width="446" alt="Screenshot 2023-09-21 at 09 35 09" src="https://github.com/SourcePointUSA/ios-cmp-app/assets/35912614/df6847f7-f477-4e66-884c-7ab85bbd30d3">

** About your environment **
 - SDK version 6.7.0
 - Device: iPhone SE, iPhone 14 Pro Max
 - OS: iOS 16, iOS 17

** To Reproduce**
1. Trigger the CMP screen as shown in the screenshot
2. Tap on the "Einstellungen oder ablehnen"

**Expected behavior**
[onAction(_ action: SPAction, from controller: UIViewController)](https://github.com/SourcePointUSA/ios-cmp-app#onAction) is triggered, allowing the app to track the event.

**Comment by andresilveirah** [comment]
Hi @timdolenko from the bug description, I'm not sure what's the issue. `onAction` is not being called?

**Comment by timdolenko** [comment]
Thanks for the prompt reply, I will update the SDK on our side

**Comment by timdolenko** [comment]
If works well on our side with the latest SDK Version, thank you!
