### ISSUE TITLE
Stored consentUUID empty or nil when trying to give custom consent

### ISSUE THREAD

**Issue by TimoWaelischIdealo** [SourcePointUSA/ios-cmp-app#496]
On a clean install and after an initial `loadMessage` call, a native message is fetched and displayed. When then trying to give a custom consent via `customConsentGDPR` I am running into the onError delegate, telling me:
```
Tried to post consent but the stored consentUUID is empty or nil. Make sure to call .loadMessage or .loadGDPRPrivacyManager or loadCCPAPrivacyManager.
```

After e.g. opening the privacy manager again afterwards, the function works again, but it should already work in the above situation since loadMessage was already called. I double-checked that this is the same instance of the consent manager. When debugging into your `SourcepointClientCoordinator`, I can see that `state.gdpr?.uuid` is indeed `nil`.

** About your environment **
 - SDK version 7.3.0
 - Device: Tested on simulator (Xcode 15.0.0 RC)
 - OS: 17.0

**Comment by TimoWaelischIdealo** [comment]
Is there any update/confirmation on this topic?

**Comment by TimoWaelischIdealo** [comment]
Hi @andresilveirah, thanks for the feedback. I will try to extract the problem into an example project, but it might take a little while.

**Comment by andresilveirah** [comment]
@TimoWaelischIdealo did you have the chance to isolate the issue?

**Comment by TimoWaelischIdealo** [comment]
Sorry, it's still on my to-do list, but priorities shifted. Should we close this for now and re-open later if necessary?

**Comment by andresilveirah** [comment]
No worries! Yes, let's close it for now, feel free to open a new issue if this is still happening.
