### ISSUE TITLE
7.4.2: SIGABRT when deploying to iOS device

### ISSUE THREAD

**Issue by appdev-exaring** [SourcePointUSA/ios-cmp-app#507]
**Describe the bug**
The app crashes when trying to load the SDK.

** About your environment **
 - SDK version 7.4.2
 - Device: iPhone 14 Pro
 - OS: 17.0.1

** To Reproduce**
1. Deploy an app with the 7.4.2 SDK to an iOS device
2. See error

```
dyld[6790]: Library not loaded: @rpath/ConsentViewController.framework/ConsentViewController
  Referenced from: <977B4983-AEF3-3792-BE5A-6CC1D3AE83C5> /private/var/containers/Bundle/Application/037DDDA6-060B-41C5-96A7-B7E834E05AB6/waipu.app/waipu
  Reason: tried: '/Users/reiner/Library/Developer/Xcode/DerivedData/waipu-bugaqishcjhrdpefgbbqbbfrlgha/Build/Products/Debug-iphoneos/PackageFrameworks/ConsentViewController.framework/ConsentViewController' (no such file), '/private/preboot/Cryptexes/OS/Users/reiner/Library/Developer/Xcode/DerivedData/waipu-bugaqishcjhrdpefgbbqbbfrlgha/Build/Products/Debug-iphoneos/PackageFrameworks/ConsentViewController.framework/ConsentViewController' (no such file), '/private/var/containers/Bundle/Application/037DDDA6-060B-41C5-96A7-B7E834E05AB6/waipu.app/Frameworks/ConsentViewController.framework/ConsentViewController' (no such file), '/Users/reiner/Library/Developer/Xcode/DerivedData/waipu-bugaqishcjhrdpefgbbqbbfrlgha/Build/Products/Debug-iphoneos/PackageFrameworks/ConsentViewController.framework/ConsentViewController' (no such file), '/private/preboot/Cryptexes/OS/Users/reiner/Library/Developer/Xcode/DerivedData/waipu-bugaqishcjhrdpefgbbqbbfrlgha/Build/Products/Debug-iphoneos/PackageFrameworks/ConsentViewController.framework/ConsentViewController' (no such file), '/private/var/containers/Bundle/Application/037DDDA6-060B-41C5-96A7-B7E834E05AB6/waipu.app/Frameworks/ConsentViewController.framework/ConsentViewController' (no such file)
```

**Additional context**
The binaries for arm64 seem to be missing.

Deployment to iOS simulator works however.

**Comment by andresilveirah** [comment]
@appdev-exaring thanks for reporting this issue. How did you integrate the SDK with your project? Via cocoapods, SPM or standalone XCFrameworks?

**Comment by appdev-exaring** [comment]
Via SPM (this is the cowoker of @asshoffm) ;-)

**Comment by appdev-exaring** [comment]
On tvOS simulator, the app does not crash, however I get the following error: `The SDK got an unexpected response from /message/gdpr endpoint` (`InvalidResponseMessageGDPREndpointError`.

- Account-Id: 1148
- PrivacyManagerId: 742851
- PropertyId: 29043

**Comment by andresilveirah** [comment]
Gotcha, so we have two issues. I think I have all info I need to work on the SPM issue. 

As for the error `InvalidResponseMessageGDPREndpointError`, I checked your campaign and I believe you're using the wrong message/pm id. 

When creating a message for tvOS, you need to choose "Native OTT" instead of "OTT / CTV". We call it "Native" because tvOS doesn't support html based messages (like the one used on other platforms). 
<img width="240" alt="Screenshot 2023-10-30 at 16 29 04" src="https://github.com/SourcePointUSA/ios-cmp-app/assets/228650/5f041bad-a905-4cc0-8386-5d8c2c419054">

It seems you already have a native message created with id `865241`. Can you try that one?

Also, keep in mind you're running a Stage campaign, so make sure to set the `campaignEnv` to stage when initialising the SDK:
```swift
campaigns: SPCampaigns(
    gdpr: SPCampaign()
    environment: .Stage
),

```

**Comment by appdev-exaring** [comment]
Same error with the above id.

This is the data we're using:

```swift
let consentServiceConfig = ConsentServiceConfiguration(environment: .stage,
                                                               accountId: 1148,
                                                               propertyName: "waipu-OTT-AppleTV-DEV",
                                                               propertyId: 29043,
                                                               privacyManagerId: 865241,
                                                               backendEnvironment: .dev)
```

BTW – are the Ids above sensitive information?!

**Comment by andresilveirah** [comment]
Hey @appdev-exaring I just noticed there was no Vendor List associated with the property you're using.
<img width="200" alt="Screenshot 2023-10-31 at 09 03 10" src="https://github.com/SourcePointUSA/ios-cmp-app/assets/228650/bd797469-8999-4185-94f7-7057cd05b394">

I took the liberty to add that property to the first Vendor List you have in your account, but I think it's worth reaching out to your account manager to have a look at your campaign, vendors, etc. 


After I added the vendor list, the error was gone for me. Can you give it another try?

>  are the Ids above sensitive information?!
No :)

**Comment by appdev-exaring** [comment]
The problem is that `ConsentViewController` is linked (indirectly) via a framework (`MyFramework`) that linked from the main app.

I created a sample project to show our setup: [SourcePointTest.zip](https://github.com/SourcePointUSA/ios-cmp-app/files/13237393/SourcePointTest.zip)

**Comment by appdev-exaring** [comment]
We have found a solution to our setup via https://stackoverflow.com/a/40128696:

> Nesting frameworks doesn't let you reuse those frameworks. For instance, if A.framework and B.framework both depend on Other.framework, then neither of them can nest Other.framework—otherwise you might end up with 2 different versions, and the correct one might not be chosen at runtime.
The correct way to do this is to list it as a dependency, but link it into the app target.

So in our case:

1. Add `ConsentViewController` to `MyFramework` as package dependency
2. In the "Build Phases" panel of `MyFramework` in "Link Binary with Libraries", change the "Status" to "Optional"
3. Add `ConsentViewController`to "MyApp" (the app target) as package dependency
4. In the "General" panel of `MyApp` in "Frameworks, Libraries ...", make sure `ConsentViewController` is added
5. In the "Build Phases" panel of. `MyApp` in "Link Binary with Libraries", make sure the the "Status" is "Required"

The updated project compiles also on iOS devices:
[SourcePointTest-fixed.zip](https://github.com/SourcePointUSA/ios-cmp-app/files/13252209/SourcePointTest-fixed.zip)

**Comment by appdev-exaring** [comment]
@andresilveirah You might want to mention this configuration in your README.

**Comment by andresilveirah** [comment]
Oh boy, what a journey. Thank you for sharing back the solution for your case @appdev-exaring . I'll add that to the README.
