### ISSUE TITLE
SwiftUI Support

### ISSUE THREAD

**Issue by jamesrb1** [SourcePointUSA/ios-cmp-app#527]
Hello!

I need to integrate this SDK with a SwiftUI project. It would be easier and faster if it had a SwiftUI interface readily available. As it is, your customers will need to write (and maintain) [glue code](https://developer.apple.com/documentation/swiftui/uiviewcontrollerrepresentable) in order to integrate it into a SwiftUI project.

Thank you,

James

**Comment by andresilveirah** [comment]
Hi @jamesrb1 , that's correct, at this stage, customers need to implement their own bridge code to support SwiftUI. We are planning to implement it ourselves, but probably only on Q2 next year.
