### ISSUE TITLE
Passing Google Additional Consent to Google Mobile Ads

### ISSUE THREAD

**Issue by mobru** [SourcePointUSA/ios-cmp-app#531]
Heya,

I am trying to figure out how to pass the "Google Additional Consent" (that is stored in the `UserDefaults` > `IABTCF_AddtlConsent`, see [documentation](https://github.com/SourcePointUSA/ios-cmp-app#google-additional-consent-gdpr-tcf)) to our Google Mobile Ads SDK. Unfortunately, I have no idea how to do so :/

According to the documentation, I have to "[l]ook for that key in the user's local storage and pass the value to Google's SDKs."  
How should this be done? Is there even anything I actually need to actively do? Because when looking at [Google's documentation here](https://support.google.com/admanager/answer/9681920?hl=en), it reads like there actually is nothing to do code-wise?

---

Environment:
* Xcode 15.0.1, Deployment Target: 12.0
* ConsentViewController (7.4.4)
* Google-Mobile-Ads-SDK (10.14.0)

**Comment by andresilveirah** [comment]
@mobru as far as I'm aware, all IAB fields are automatically picked by by IAB vendors. In theory, you don't have to do anything. 

If you still need to read that value, you can do so by calling the following code inside either `onConsentReady` or `onSPFinished`
```swift
let value = UserDefaults.standard.string(forKey: "IABTCF_AddtlConsent")
```
