### ISSUE TITLE
Revoking previously given consent

### ISSUE THREAD

**Issue by mobru** [SourcePointUSA/ios-cmp-app#532]
Environment:
* Xcode 15.0.1, Deployment Target: 12.0
* ConsentViewController (7.4.4)

---

I'm having issues with revoking previously given consent:

### via `SPConsentManager.clearAllData()`
Calling `SPConsentManager.clearAllData()` programmatically (from a `UIButton` action outside the Sourcepoint environment) appears to be resetting everything (e.g. the `IABTCF_AddtlConsent` in the `UserDefaults` is `nil`), but after a new app start (right after calling `SPConsentManager.clearAllData()`), all consent is "back" again (`userData.gdpr!.consents!.consentStatus.rejectedAny == false`, `IABTCF_AddtlConsent` is `"1~xyz"`).

### ~via `RejectAll`~
~Consent does appear to be set to `false` via a `RejectAll` action triggered by a button we put in our Privacy Manager (`userData.gdpr!.consents!.consentStatus.consentedToAny == false`), but then the `SPDelegate` method `onSPUIReady(_:)` is not called - instead `loadMessage(forAuthId:publisherData:)` only triggers `onConsentReady(userData:)`, and that's it.~  
~(if this has something to do with the configuration in the Sourcepoint dashboard - any pointers where the issue might be?)~  
EDIT: via `RejectAll` works, was an issue with the configuration.

**Comment by andresilveirah** [comment]
@mobru we currently don't support programmatically revoking consents of a user. You can, however, grant/remove GDPR consent to vendors / purpose that are not part of the IAB (we call them custom vendors / purposes). Please have a look at https://github.com/SourcePointUSA/ios-cmp-app#adding-or-removing-custom-consents

The method `SPConsentManager.clearAllData()` is local only. After calling it, the SDK will remove consent data locally, but if your app calls `.loadMessage()` with an `authId` the SDK will bring the consents stored in the server back to the device. If no `authId` is passed, the user is going through the message flow and scenario setup for your property.
