### ISSUE TITLE
SPCampaigns initializer, ios14 parameter

### ISSUE THREAD

**Issue by mobru** [SourcePointUSA/ios-cmp-app#533]
Environment:
* Xcode 15.0.1, Deployment Target: 12.0
* ConsentViewController (7.4.4)

---

Quick question about the initializer for `SPCampaigns`, namely the `ios14` parameter - what is this used for / what is its intention? I can find nothing in the documentation / readme about this.

I am currently just using the same `SPCampaign` for both the `gdpr` and the `ios14` parameters, e.g.:
```swift
let campgain = SPCampaign(targetingParams: ["foo" : "bar"])
let campaigns = SPCampaigns(gdpr: campaign, ios14: campaign)
let manager = SPConsentManager(accountId: 123,
                               propertyId: 456,
                               propertyName: "789",
                               campaigns: campaigns,
                               delegate: self)
```

Is this the intended way of using this parameter?

**Comment by mobru** [comment]
@andresilveirah The account manager already is on their Christmas vacation, I'm afraid :)  
Anyway - thank you for clarifying!

**Comment by andresilveirah** [comment]
@mobru Oh no 🎅 Are there no one covering for him/her? If you ran out of support, I'll be your account manager, don't worry.

**Comment by mobru** [comment]
@andresilveirah not sure, I am not in direct contact with anyone from Sourcepoint, the customer I'm working for is.  
Anyhow - thank you very much for your offer, I'll email you (with all our our customer's information) if we do need anything else!
