### ISSUE TITLE
`onSPUIReady` not called on some devices

### ISSUE THREAD

**Issue by jamesrb1** [SourcePointUSA/ios-cmp-app#534]
**Describe the bug**

On some hardware, we never get the callback to show the privacy dialog. We added some rudimentary logging for our aflicted QA device, and it shows that we are never asked to show the UI (see screenshots below).

This seems to be consistently reproducible on specific devices. We are also seeing the same problem with one iPhone.

**About your campaign (please complete the following information):**
 - Account Id: 1917
 - Property Id: 33373
 - Property Name: ctv.kidoodle.tv
 - Campaign Env
 - PrivacyManager Id
 - Targeting Params (if any)
 - AuthId (if any)

** About your environment **
 - SDK version 7.4.4
 - Device: [e.g. iPhone6] AppleTV 3rd Gen
 - OS: [e.g. iOS8.1] 17.2 (tvOS and iOS)

** To Reproduce**

Integrate the SDK and it doesn't work on some hardware.

**Expected behavior**
We expect it to require the user be prompted when `loadMessage` is called for the first time with no ID or when it sees a particular ID for the first time.

**Screenshots**
Showing our rudimentary log, using a clean install, calling showMessage without an ID:

![IMG_6150](https://github.com/SourcePointUSA/ios-cmp-app/assets/109382862/cd08e252-b2ca-4cef-88a6-c446afee4337)

After creating a new ID:
![IMG_0098](https://github.com/SourcePointUSA/ios-cmp-app/assets/109382862/afaa3974-25e4-4bc5-be9a-36bd2fe63e46)

**Additional context**
### Code for logging:
```
if let controller = dataController?.defaultContext, let user = KTUser.currentUser(in: controller), !user.guestAccount {
                KTLogger.shared.addMessage("loadmessage with id: \(user.identifier)")
                consentManager.loadMessage(forAuthId: user.identifier)
            } else {
                KTLogger.shared.addMessage("loadmessage without id")
                consentManager.loadMessage()
            }
```
Logging is also included in each delegate callback.

### Code that creates the consent manager:
```
lazy var consentManager: SPSDK = { SPConsentManager(
        accountId: 1917,
        propertyId: 33373,
        propertyName: try! SPPropertyName("ctv.kidoodle.tv"),
        campaigns: SPCampaigns(
            gdpr: SPCampaign(),
            ccpa: SPCampaign()
        ),
        delegate: self
    )}()
```

**Comment by andresilveirah** [comment]
Hi @jamesrb1 I see you have a geolocation filter in your scenario. Messages should only show if the user is in the EEA, UK or Canada, according to that filter. Is the device in one of those locations?

And, are you able to see the consent message in any other device / emulator within the same setup?

**Comment by jamesrb1** [comment]
Thank you, this does seem likely to be the cause. We can consider this resolved. Thanks for you help!
